name: Generate github production tag

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '--skip-tagging')"
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install node dependencies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Build node dependencies
        run: yarn build

      - name: Remove developer folders
        run: |
          rm -r -f tests/
          rm -r -f build/
          rm -r -f node_modules/
          rm -r -f .vscode/
          rm -r -f .parcel-cache/
          rm -r -f tests/

      - name: Remove developer files
        run: |
          rm -f composer.json
          rm -f composer.lock
          rm -f package.json
          rm -f package-json.lock
          rm -f yarn.lock
          rm -f README.md
          rm -f .gitignore
          rm -f tsconfig.json
          rm -f phpunit.xml

      - name: Create a new GitHub tag
        run: |
          TAG_VERSION=$(bash .github/tags.sh)
          rm -r -f .github/

          git config --global user.email "aguiartgv@gmail.com"
          git config --global user.name "Matheus Aguiar"

          git add .
          git commit -am "build: Building a new version"

          git tag -a v$TAG_VERSION -m "New tag: v$TAG_VERSION"
          git push origin v$TAG_VERSION

          echo "All right! 🍕"
