name: Generate github stage tag

on:
  push:
    branches: ["stage"]
  pull_request:
    branches: ["stage"]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '--skip-tagging')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install node dependencies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Build node dependencies
        run: yarn build

      - name: Remove cache folder
        run: |
          rm -r -f .parcel-cache/

      - name: Remove git files
        run: |
          rm -f .gitignore

      - name: Create a new GitHub stage tag
        run: |
          TAG_VERSION=$(bash .github/tag.sh)

          git config --global user.email "aguiartgv@gmail.com"
          git config --global user.name "Matheus Aguiar"

          git add .
          git commit -am "build: Building a new developer version"

          git tag -a v$TAG_VERSION-dev -m "New developer tag: v$TAG_VERSION-dev"
          git push origin v$TAG_VERSION-dev

          echo "All right! 🍕"
