name: PHP Composer

on:
  push:
    branches: [ "master", "stage" ]
  pull_request:
    branches: [ "master", "stage" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Install node dependencies
      run: yarn install --frozen-lockfile --prefer-offline

    - name: Build node dependencies
      run: yarn build
      
    - name: Remove developer folders
      run: |
            rm -r node_modules/
            rm -r resources/
            rm -r .git/
            
    - name: Remove developer files
      run: |
            rm composer.json composer.lock
            rm package.json yarn.lock
            rm README.md tsconfig.json .gitignore.json

