name: PHP Composer

on:
  push:
    branches: [ "master", "stage" ]
  pull_request:
    branches: [ "master", "stage" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Install node dependencies
      run: yarn install --frozen-lockfile --prefer-offline

    - name: Build node dependencies
      run: yarn build
      
    - name: Remove developer folders
      run: |
            rm -r node_modules/
            rm -r resources/
            rm -r .github/
            
    - name: Remove developer files
      run: |
            rm composer.json package.json composer.lock
            rm README.md tsconfig.json .gitignore
            
    - name: Create a new GitHub tag
      run: |
            git config --global user.email "contato@codebakery.com.br"
            git config --global user.name "Code Bakery"
            
            git commit -am "build: Building a new version"
            
            echo ${{ bash ./.github/tags/next.sh }}
            
            git tag -a ${{ bash ./.github/tags/next.sh }} -m "Release: ${{ bash ./.github/tags/next.sh }}"
            git push origin ${{ bash ./.github/tags/next.sh }}
            
            echo ${{ bash ./.github/tags/next.sh }}
            echo "All right! 🍕"

