name: PHP Composer

on:
  push:
    branches: [ "master", "stage" ]
  pull_request:
    branches: [ "master", "stage" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Install node dependencies
      run: yarn install --frozen-lockfile --prefer-offline

    - name: Build node dependencies
      run: yarn build
      
    - name: Remove developer folders
      run: |
            rm -r node_modules/
            rm -r resources/
            rm -r .github/
            
    - name: Remove developer files
      run: |
            rm composer.json package.json composer.lock
            rm README.md tsconfig.json .gitignore
            
    - name: Generate the next tag version
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Create a GitHub tag
      run: |
            git config --global user.email "contato@codebakery.com.br"
            git config --global user.name "Code Bakery"
            
            git commit -am "build: Building a new version"
            
            git tag -a ${{ steps.tag_version.outputs.new_tag }} -m "Release: ${{ steps.tag_version.outputs.new_tag }}"
            git push origin ${{ steps.tag_version.outputs.new_tag }}
            
            echo "All right! 🍕"

