name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Install node dependencies
      run: yarn install --frozen-lockfile --prefer-offline

    - name: Build node dependencies
      run: yarn build
    
    - name: Generate a new tag name
      run: |
        NEXT_VERSION=$(bash ./.github/tags/next.sh)
      
    - name: Remove developer folders
      run: |
            rm -r node_modules/
            rm -r resources/
            rm -r .github/
            
    - name: Remove developer files
      run: |
            rm composer.json package.json composer.lock
            rm README.md tsconfig.json .gitignore
            
    - name: Create a new GitHub tag
      run: |
            git config --global user.email "contato@codebakery.com.br"
            git config --global user.name "Code Bakery"
            
            git commit -am "build: Building a new version"
            
            git tag -a $NEXT_VERSION -m "Release: $NEXT_VERSION"
            git push origin $NEXT_VERSION
            
            echo $NEXT_VERSION
            echo "All right! 🍕"

