name: PHP Composer

on:
  push:
    branches: [ "master", "stage" ]
  pull_request:
    branches: [ "master", "stage" ]

permissions:
  contents: read
  
env:
  LAST_TAG: git describe --tags --abbrev=0
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Install node dependencies
      run: yarn install --frozen-lockfile --prefer-offline

    - name: Build node dependencies
      run: yarn build
      
    - name: Remove developer folders
      run: |
            rm -r node_modules/
            rm -r resources/
            
    - name: Remove developer files
      run: |
            rm composer.json package.json composer.lock
            rm README.md tsconfig.json .gitignore
    
    - name: Tag a new version
      run: |
            git config --global user.email "contato@codebakery.com.br"
            git config --global user.name "Code Bakery"
            
            git tag -a ${{github.run_id}} -m "New version: ${{github.run_id}}"
            git push origin ${{github.run_id}}

