name: Generate GitHub Tag

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Install node dependencies
      run: yarn install --frozen-lockfile --prefer-offline

    - name: Build node dependencies
      run: yarn build
      
    - name: Remove developer folders
      run: |
            rm -r node_modules/
            rm -r resources/
            
    - name: Remove developer files
      run: |
            rm composer.json package.json composer.lock
            rm README.md tsconfig.json .gitignore
            
    - name: Create a new GitHub developer tag
      run: |
            git tag -a dev-${{github.run_id}} -m "New developer tag: ${{github.run_id}}"
            git push origin dev-${{github.run_id}}

    - name: Create a new GitHub prod tag
      run: |
            git commit -am "build: Building a new version"
            
            git tag -a prod-${{github.run_id}} -m "New tag: ${{github.run_id}}"
            git push origin prod-${{github.run_id}}

            
            echo $NEXT_VERSION
            echo "All right! 🍕"

